name: python-application-workflow

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: setup-workflow
          uses: actions/setup-python@v2
          with:
                python-version: '3.8'
